PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128

MIN_NAME_LENGTH = 2
MAX_NAME_LENGTH = 100

EMAIL_MAX_LENGTH = 255

VERIFICATION_TOKEN_BYTES = 48
PASSWORD_RESET_TOKEN_BYTES = 48
API_KEY_BYTES = 48
SESSION_TOKEN_BYTES = 48

EMAIL_VERIFICATION_EXPIRY_HOURS = 24
PASSWORD_RESET_EXPIRY_HOURS = 1

BCRYPT_ROUNDS = 12
