from __future__ import annotations

from html import escape

from app.services.security.executive_summary import (
    ExecutiveSummaryGenerator,
)
from app.services.security.models import (
    SecurityAnalysisResult,
)


class HtmlSecurityReport:

    @classmethod
    def generate(
        cls,
        result: SecurityAnalysisResult,
    ) -> str:

        summary = (
            ExecutiveSummaryGenerator.generate(
                result
            )
        )

        rows = []

        for assessment in result.assessments:

            rows.append(
                f"""
<tr>
<td>{escape(assessment.method)}</td>
<td>{escape(assessment.path)}</td>
<td>{assessment.score}</td>
<td>{escape(assessment.severity.value)}</td>
<td>{len(assessment.findings)}</td>
</tr>
"""
            )

        return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>API Sentry Security Report</title>

<style>

body{{
font-family:Arial,sans-serif;
background:#f6f8fb;
margin:30px;
}}

h1{{
margin-bottom:5px;
}}

.card{{
background:#fff;
padding:20px;
border-radius:10px;
margin-bottom:20px;
box-shadow:0 2px 8px rgba(0,0,0,.08);
}}

table{{
width:100%;
border-collapse:collapse;
}}

th,td{{
padding:10px;
border-bottom:1px solid #ddd;
text-align:left;
}}

th{{
background:#eceff5;
}}

.metric{{
display:inline-block;
margin-right:35px;
font-size:18px;
}}

.footer{{
margin-top:40px;
font-size:12px;
color:#666;
}}

</style>

</head>

<body>

<h1>API Sentry Security Report</h1>

<div class="card">

<div class="metric">
<b>Score</b><br>
{summary["overall_score"]}
</div>

<div class="metric">
<b>Grade</b><br>
{summary["risk_grade"]}
</div>

<div class="metric">
<b>Severity</b><br>
{summary["overall_severity"]}
</div>

<div class="metric">
<b>Findings</b><br>
{summary["finding_count"]}
</div>

</div>

<div class="card">

<h2>Endpoint Analysis</h2>

<table>

<tr>
<th>Method</th>
<th>Path</th>
<th>Score</th>
<th>Severity</th>
<th>Findings</th>
</tr>

{''.join(rows)}

</table>

</div>

<div class="footer">

Generated by API Sentry

</div>

</body>

</html>
"""
