"""create api discovery tables

Revision ID: aa789c9d234d
Revises: 3fd05ee5aa5b
Create Date: 2026-07-19 07:39:14.479237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa789c9d234d'
down_revision: Union[str, Sequence[str], None] = '3fd05ee5aa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovered_apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('scan_job_id', sa.Integer(), nullable=True),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS', 'HEAD', 'TRACE', 'CONNECT', 'ANY', name='http_method', native_enum=False), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('normalized_path', sa.String(length=1000), nullable=False),
    sa.Column('router_prefix', sa.String(length=500), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('controller_name', sa.String(length=255), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('source_file', sa.String(length=1000), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('end_line_number', sa.Integer(), nullable=True),
    sa.Column('authentication_required', sa.Boolean(), nullable=False),
    sa.Column('authentication_type', sa.Enum('PUBLIC', 'JWT', 'API_KEY', 'BASIC', 'BEARER', 'SESSION', 'OAUTH2', 'CUSTOM', 'UNKNOWN', name='authentication_type', native_enum=False), nullable=False),
    sa.Column('authentication_details', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('request_body_model', sa.String(length=255), nullable=True),
    sa.Column('response_model', sa.String(length=255), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('discovery_status', sa.Enum('ACTIVE', 'REMOVED', 'IGNORED', name='discovery_status', native_enum=False), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'http_method', 'path', 'source_file', 'line_number', name='uq_discovered_api_location')
    )
    op.create_index(op.f('ix_discovered_apis_id'), 'discovered_apis', ['id'], unique=False)
    op.create_index(op.f('ix_discovered_apis_project_id'), 'discovered_apis', ['project_id'], unique=False)
    op.create_index('ix_discovered_apis_project_method', 'discovered_apis', ['project_id', 'http_method'], unique=False)
    op.create_index('ix_discovered_apis_project_path', 'discovered_apis', ['project_id', 'path'], unique=False)
    op.create_index(op.f('ix_discovered_apis_scan_job_id'), 'discovered_apis', ['scan_job_id'], unique=False)
    op.create_table('api_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovered_api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.Enum('PATH', 'QUERY', 'HEADER', 'COOKIE', 'BODY', 'FORM', 'FILE', 'DEPENDENCY', 'UNKNOWN', name='parameter_location', native_enum=False), nullable=False),
    sa.Column('data_type', sa.String(length=255), nullable=True),
    sa.Column('schema_reference', sa.String(length=500), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('example_value', sa.Text(), nullable=True),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovered_api_id'], ['discovered_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discovered_api_id', 'name', 'location', name='uq_api_parameter_name_location')
    )
    op.create_index('ix_api_parameters_api_location', 'api_parameters', ['discovered_api_id', 'location'], unique=False)
    op.create_index(op.f('ix_api_parameters_discovered_api_id'), 'api_parameters', ['discovered_api_id'], unique=False)
    op.create_index(op.f('ix_api_parameters_id'), 'api_parameters', ['id'], unique=False)
    op.create_table('api_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discovered_api_id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('response_model', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('example_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovered_api_id'], ['discovered_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discovered_api_id', 'status_code', name='uq_api_response_status')
    )
    op.create_index(op.f('ix_api_responses_discovered_api_id'), 'api_responses', ['discovered_api_id'], unique=False)
    op.create_index(op.f('ix_api_responses_id'), 'api_responses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_responses_id'), table_name='api_responses')
    op.drop_index(op.f('ix_api_responses_discovered_api_id'), table_name='api_responses')
    op.drop_table('api_responses')
    op.drop_index(op.f('ix_api_parameters_id'), table_name='api_parameters')
    op.drop_index(op.f('ix_api_parameters_discovered_api_id'), table_name='api_parameters')
    op.drop_index('ix_api_parameters_api_location', table_name='api_parameters')
    op.drop_table('api_parameters')
    op.drop_index(op.f('ix_discovered_apis_scan_job_id'), table_name='discovered_apis')
    op.drop_index('ix_discovered_apis_project_path', table_name='discovered_apis')
    op.drop_index('ix_discovered_apis_project_method', table_name='discovered_apis')
    op.drop_index(op.f('ix_discovered_apis_project_id'), table_name='discovered_apis')
    op.drop_index(op.f('ix_discovered_apis_id'), table_name='discovered_apis')
    op.drop_table('discovered_apis')
    # ### end Alembic commands ###
